fus_gse <- readRDS("~/ALS/genes/GSEA/clean/fus_GSEA_cleaned.RDS")
mfa_gse <-readRDS("~/ALS/genes/GSEA/clean/M6a_GSEA_cleaned.RDS")
multi_gse <- readRDS("~/ALS/genes/GSEA/clean/multi_GSEA_cleaned.RDS")
polo_gse <- readRDS("~/ALS/genes/GSEA/clean/polo_GSEA_cleaned.RDS")
swift_gse <- readRDS("~/ALS/genes/GSEA/clean/swift_GSEA_cleaned.RDS")
write.csv(fus_gse,"GSE94888-gsea.csv", row.names = FALSE)
write.csv(mfa_gse,"GSE242766-gsea.csv", row.names = FALSE)
write.csv(multi_gse,"GSE276214-gsea.csv", row.names = FALSE)
write.csv(polo_gse,"GSE272827-gsea.csv", row.names = FALSE)
write.csv(swift_gse,"GSE229095-gsea.csv",row.names = FALSE)
astro_gse <- readRDS("~/ALS/genes/GSEA/gsea_astor.RDS")
astro_gsea <- as.data.frame(astro_gse)
library(dplyr)
astro_go_res <- astro_gsea %>% select(ID,Description,NES,p.adjust) %>% arrange(desc(NES))
write.csv(astro_go_res,"GSE196219-gsea.csv", row.names = FALSE)
